/**
 *
 * $Id$
 */
package com.w3schools.validation;

import com.w3schools.Description;
import com.w3schools.Performance;

/**
 * A sample validator interface for {@link com.w3schools.Hwmapping}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HwmappingValidator {
	boolean validate();

	boolean validateMappingname(String value);
	boolean validatePerformance(Performance value);
	boolean validateDescription(Description value);
}
