/**
 *
 * $Id$
 */
package com.w3schools.validation;

import com.w3schools.LoopType;
import com.w3schools.SubmoduleType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.w3schools.SubmodulesType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SubmodulesTypeValidator {
	boolean validate();

	boolean validateSubmodule(EList<SubmoduleType> value);
	boolean validateLoop(EList<LoopType> value);
}
