/**
 *
 * $Id$
 */
package com.w3schools.validation;


/**
 * A sample validator interface for {@link com.w3schools.AppSpecificationsType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AppSpecificationsTypeValidator {
	boolean validate();

	boolean validateApplicationname(String value);
	boolean validateCpucycles(int value);
	boolean validateBuscycles(int value);
}
