/**
 *
 * $Id$
 */
package com.w3schools.validation;

import com.w3schools.LoopSpecificationsType;

/**
 * A sample validator interface for {@link com.w3schools.LoopType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LoopTypeValidator {
	boolean validate();

	boolean validateSpecifications(LoopSpecificationsType value);
}
