// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xgray_scale.h"

/************************** Function Implementation *************************/
int XGray_scale_Initialize(XGray_scale *InstancePtr, XGray_scale_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}

void XGray_scale_Start(XGray_scale *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGray_scale_ReadReg(InstancePtr->Control_bus_BaseAddress, XGRAY_SCALE_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XGray_scale_WriteReg(InstancePtr->Control_bus_BaseAddress, XGRAY_SCALE_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XGray_scale_IsDone(XGray_scale *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGray_scale_ReadReg(InstancePtr->Control_bus_BaseAddress, XGRAY_SCALE_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XGray_scale_IsIdle(XGray_scale *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGray_scale_ReadReg(InstancePtr->Control_bus_BaseAddress, XGRAY_SCALE_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XGray_scale_IsReady(XGray_scale *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGray_scale_ReadReg(InstancePtr->Control_bus_BaseAddress, XGRAY_SCALE_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XGray_scale_EnableAutoRestart(XGray_scale *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGray_scale_WriteReg(InstancePtr->Control_bus_BaseAddress, XGRAY_SCALE_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XGray_scale_DisableAutoRestart(XGray_scale *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGray_scale_WriteReg(InstancePtr->Control_bus_BaseAddress, XGRAY_SCALE_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XGray_scale_SetRows(XGray_scale *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGray_scale_WriteReg(InstancePtr->Control_bus_BaseAddress, XGRAY_SCALE_CONTROL_BUS_ADDR_ROWS_DATA, Data);
}

u32 XGray_scale_GetRows(XGray_scale *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGray_scale_ReadReg(InstancePtr->Control_bus_BaseAddress, XGRAY_SCALE_CONTROL_BUS_ADDR_ROWS_DATA);
    return Data;
}

void XGray_scale_SetCols(XGray_scale *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGray_scale_WriteReg(InstancePtr->Control_bus_BaseAddress, XGRAY_SCALE_CONTROL_BUS_ADDR_COLS_DATA, Data);
}

u32 XGray_scale_GetCols(XGray_scale *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGray_scale_ReadReg(InstancePtr->Control_bus_BaseAddress, XGRAY_SCALE_CONTROL_BUS_ADDR_COLS_DATA);
    return Data;
}

void XGray_scale_InterruptGlobalEnable(XGray_scale *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGray_scale_WriteReg(InstancePtr->Control_bus_BaseAddress, XGRAY_SCALE_CONTROL_BUS_ADDR_GIE, 1);
}

void XGray_scale_InterruptGlobalDisable(XGray_scale *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGray_scale_WriteReg(InstancePtr->Control_bus_BaseAddress, XGRAY_SCALE_CONTROL_BUS_ADDR_GIE, 0);
}

void XGray_scale_InterruptEnable(XGray_scale *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XGray_scale_ReadReg(InstancePtr->Control_bus_BaseAddress, XGRAY_SCALE_CONTROL_BUS_ADDR_IER);
    XGray_scale_WriteReg(InstancePtr->Control_bus_BaseAddress, XGRAY_SCALE_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XGray_scale_InterruptDisable(XGray_scale *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XGray_scale_ReadReg(InstancePtr->Control_bus_BaseAddress, XGRAY_SCALE_CONTROL_BUS_ADDR_IER);
    XGray_scale_WriteReg(InstancePtr->Control_bus_BaseAddress, XGRAY_SCALE_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XGray_scale_InterruptClear(XGray_scale *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGray_scale_WriteReg(InstancePtr->Control_bus_BaseAddress, XGRAY_SCALE_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XGray_scale_InterruptGetEnabled(XGray_scale *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XGray_scale_ReadReg(InstancePtr->Control_bus_BaseAddress, XGRAY_SCALE_CONTROL_BUS_ADDR_IER);
}

u32 XGray_scale_InterruptGetStatus(XGray_scale *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XGray_scale_ReadReg(InstancePtr->Control_bus_BaseAddress, XGRAY_SCALE_CONTROL_BUS_ADDR_ISR);
}

