// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.1
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Erode_16_16_1080_1920_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_rows_V_read,
        p_src_cols_V_read,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [11:0] p_src_rows_V_read;
input  [11:0] p_src_cols_V_read;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;
reg    ap_done_reg = 1'b0;
reg   [2:0] ap_CS_fsm = 3'b000;
reg    ap_sig_bdd_57;
wire   [1:0] i_3_fu_466_p2;
reg   [1:0] i_3_reg_1063;
wire   [0:0] sel_tmp37_i_fu_472_p2;
reg   [0:0] sel_tmp37_i_reg_1068;
wire   [0:0] exitcond_fu_460_p2;
wire   [0:0] sel_tmp46_i_fu_490_p2;
reg   [0:0] sel_tmp46_i_reg_1079;
wire   [0:0] sel_tmp49_i_fu_496_p2;
reg   [0:0] sel_tmp49_i_reg_1087;
wire   [1:0] indvar_next1_i_fu_508_p2;
reg   [1:0] indvar_next1_i_reg_1098;
wire   [0:0] sel_tmp58_i_fu_548_p2;
reg   [0:0] sel_tmp58_i_reg_1103;
wire   [0:0] exitcond7_fu_502_p2;
wire   [0:0] sel_tmp59_i_fu_554_p2;
reg   [0:0] sel_tmp59_i_reg_1108;
wire   [0:0] sel_tmp61_i_fu_559_p2;
reg   [0:0] sel_tmp61_i_reg_1114;
wire   [0:0] tmp_64_i_fu_570_p2;
reg   [0:0] tmp_64_i_reg_1119;
wire   [0:0] or_cond_i_fu_576_p2;
reg   [0:0] or_cond_i_reg_1126;
wire   [0:0] tmp_fu_582_p2;
reg   [0:0] tmp_reg_1133;
wire   [7:0] result_val13_5_i_fu_596_p3;
reg   [7:0] result_val13_5_i_reg_1139;
wire   [7:0] result_val26_5_i_fu_604_p3;
reg   [7:0] result_val26_5_i_reg_1144;
wire   [7:0] newSel29_i_fu_663_p3;
wire   [7:0] newSel31_i_fu_679_p3;
wire   [7:0] newSel34_i_fu_702_p3;
wire   [7:0] newSel37_i_fu_726_p3;
wire   [7:0] newSel39_i_fu_741_p3;
wire   [7:0] newSel42_i_fu_762_p3;
wire   [7:0] newSel43_i_fu_770_p3;
wire   [31:0] indvar_next_i_fu_784_p2;
reg   [31:0] indvar_next_i_reg_1187;
wire   [0:0] sel_tmp84_i_fu_834_p2;
reg   [0:0] sel_tmp84_i_reg_1192;
wire   [0:0] exitcond5_i_fu_778_p2;
wire   [0:0] sel_tmp86_i_fu_839_p2;
reg   [0:0] sel_tmp86_i_reg_1198;
wire   [0:0] sel_tmp87_i_fu_844_p2;
reg   [0:0] sel_tmp87_i_reg_1204;
wire   [0:0] sel_tmp88_i_fu_849_p2;
reg   [0:0] sel_tmp88_i_reg_1209;
wire   [0:0] or_cond36_i_fu_854_p2;
reg   [0:0] or_cond36_i_reg_1215;
wire   [0:0] or_cond38_i_fu_866_p2;
reg   [0:0] or_cond38_i_reg_1221;
wire   [0:0] or_cond41_i_fu_871_p2;
reg   [0:0] or_cond41_i_reg_1228;
wire   [7:0] result_val13_1_i_fu_885_p3;
reg   [7:0] result_val13_1_i_reg_1233;
wire   [7:0] result_val26_1_i_fu_893_p3;
reg   [7:0] result_val26_1_i_reg_1238;
wire   [7:0] newSel57_i_fu_909_p3;
reg   [7:0] newSel57_i_reg_1243;
wire   [7:0] newSel47_i_fu_953_p3;
wire   [7:0] newSel49_i_fu_968_p3;
wire   [7:0] newSel52_i_fu_990_p3;
wire   [7:0] newSel55_i_fu_1012_p3;
wire   [7:0] newSel60_i_fu_1034_p3;
wire   [7:0] newSel61_i_fu_1042_p3;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_idle;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_ready;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_dout;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_empty_n;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_dout;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_empty_n;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_dout;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_empty_n;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_din;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_full_n;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_write;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_din;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_full_n;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_write;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_din;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_full_n;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_write;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_0_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_1_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_2_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_0_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_1_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_2_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_0_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_1_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_2_read;
wire   [11:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_rows;
wire   [11:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_cols;
reg   [7:0] temp_kernel_val_0_2_reg_70;
reg   [7:0] temp_kernel_val_1_0_reg_82;
reg   [7:0] temp_kernel_val_1_1_reg_94;
reg   [7:0] temp_kernel_val_0_1_reg_106;
reg   [7:0] temp_kernel_val_1_2_reg_118;
reg   [7:0] temp_kernel_val_2_0_reg_130;
reg   [7:0] temp_kernel_val_0_0_reg_142;
reg   [7:0] temp_kernel_val_2_1_reg_154;
reg   [7:0] temp_kernel_val_2_2_reg_166;
reg   [1:0] i_reg_178;
reg   [7:0] result_val2_6_i_reg_190;
reg   [7:0] result_val13_6_i_reg_201;
reg   [7:0] result_val14_6_i_reg_212;
reg   [7:0] result_val16_6_i_reg_223;
reg   [7:0] result_val1520_6_i_reg_234;
reg   [7:0] result_val26_6_i_reg_245;
reg   [7:0] result_val_6_i_reg_256;
reg   [7:0] result_val27_6_i_reg_267;
reg   [7:0] result_val28_6_i_reg_278;
reg   [1:0] j_reg_289;
reg   [7:0] result_val2_2_i_reg_300;
reg   [7:0] result_val13_2_i_reg_312;
reg   [7:0] result_val14_2_i_reg_324;
reg   [7:0] result_val16_2_i_reg_336;
reg   [7:0] result_val1520_2_i_reg_348;
reg   [7:0] result_val26_2_i_reg_360;
reg   [7:0] result_val_2_i_reg_372;
reg   [7:0] result_val27_2_i_reg_384;
reg   [7:0] result_val28_2_i_reg_396;
reg   [31:0] indvar_i_reg_408;
reg    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg = 1'b0;
wire   [0:0] sel_tmp44_i_fu_478_p2;
wire   [0:0] sel_tmp45_i_fu_484_p2;
wire   [0:0] sel_tmp38_i_fu_514_p2;
wire   [0:0] sel_tmp52_i_fu_530_p2;
wire   [0:0] sel_tmp54_i_fu_536_p2;
wire   [1:0] tmp_63_i_fu_564_p2;
wire   [0:0] sel_tmp47_i_fu_525_p2;
wire   [0:0] sel_tmp39_i_fu_520_p2;
wire   [0:0] tmp1_i_fu_542_p2;
wire   [7:0] sel_tmp62_i_fu_588_p3;
wire   [0:0] or_cond8_i_fu_616_p2;
wire   [0:0] or_cond9_i_fu_620_p2;
wire   [7:0] newSel_i_fu_624_p3;
wire   [0:0] grp_fu_456_p2;
wire   [0:0] or_cond11_i_fu_631_p2;
wire   [7:0] newSel27_i_fu_636_p3;
wire   [0:0] or_cond12_i_fu_644_p2;
wire   [0:0] or_cond13_i_fu_657_p2;
wire   [7:0] newSel28_i_fu_649_p3;
wire   [0:0] sel_tmp60_i_fu_612_p2;
wire   [7:0] newSel30_i_fu_671_p3;
wire   [7:0] newSel32_i_fu_687_p3;
wire   [7:0] newSel33_i_fu_694_p3;
wire   [7:0] newSel35_i_fu_710_p3;
wire   [7:0] newSel36_i_fu_718_p3;
wire   [7:0] newSel38_i_fu_734_p3;
wire   [7:0] newSel40_i_fu_748_p3;
wire   [7:0] newSel41_i_fu_755_p3;
wire   [1:0] tmp_103_fu_790_p1;
wire   [0:0] sel_tmp72_i_fu_794_p2;
wire   [0:0] sel_tmp80_i_fu_810_p2;
wire   [0:0] sel_tmp81_i_fu_816_p2;
wire   [0:0] sel_tmp83_i_fu_828_p2;
wire   [0:0] sel_tmp77_i_fu_805_p2;
wire   [0:0] sel_tmp73_i_fu_800_p2;
wire   [0:0] tmp29_i_fu_822_p2;
wire   [0:0] tmp3_fu_860_p2;
wire   [7:0] sel_tmp89_i_fu_877_p3;
wire   [7:0] newSel56_i_fu_901_p3;
wire   [0:0] or_cond37_i_fu_917_p2;
wire   [7:0] newSel44_i_fu_921_p3;
wire   [0:0] or_cond40_i_fu_928_p2;
wire   [7:0] newSel45_i_fu_933_p3;
wire   [0:0] or_cond42_i_fu_948_p2;
wire   [7:0] newSel46_i_fu_940_p3;
wire   [7:0] newSel48_i_fu_961_p3;
wire   [7:0] newSel50_i_fu_976_p3;
wire   [7:0] newSel51_i_fu_983_p3;
wire   [7:0] newSel53_i_fu_998_p3;
wire   [7:0] newSel54_i_fu_1005_p3;
wire   [7:0] newSel58_i_fu_1020_p3;
wire   [7:0] newSel59_i_fu_1027_p3;
reg   [2:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 3'b000;
parameter    ap_ST_st2_fsm_1 = 3'b1;
parameter    ap_ST_st3_fsm_2 = 3'b10;
parameter    ap_ST_st4_fsm_3 = 3'b11;
parameter    ap_ST_st5_fsm_4 = 3'b100;
parameter    ap_ST_st6_fsm_5 = 3'b101;
parameter    ap_ST_st7_fsm_6 = 3'b110;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv8_1 = 8'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_true = 1'b1;


filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start ),
    .ap_done( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done ),
    .ap_idle( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_idle ),
    .ap_ready( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_ready ),
    .p_src_data_stream_0_V_dout( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_dout ),
    .p_src_data_stream_0_V_empty_n( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_empty_n ),
    .p_src_data_stream_0_V_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_read ),
    .p_src_data_stream_1_V_dout( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_dout ),
    .p_src_data_stream_1_V_empty_n( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_empty_n ),
    .p_src_data_stream_1_V_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_read ),
    .p_src_data_stream_2_V_dout( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_dout ),
    .p_src_data_stream_2_V_empty_n( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_empty_n ),
    .p_src_data_stream_2_V_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_read ),
    .p_dst_data_stream_0_V_din( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_din ),
    .p_dst_data_stream_0_V_full_n( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_full_n ),
    .p_dst_data_stream_0_V_write( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_write ),
    .p_dst_data_stream_1_V_din( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_din ),
    .p_dst_data_stream_1_V_full_n( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_full_n ),
    .p_dst_data_stream_1_V_write( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_write ),
    .p_dst_data_stream_2_V_din( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_din ),
    .p_dst_data_stream_2_V_full_n( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_full_n ),
    .p_dst_data_stream_2_V_write( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_write ),
    .kernel_val_0_0_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_0_read ),
    .kernel_val_0_1_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_1_read ),
    .kernel_val_0_2_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_2_read ),
    .kernel_val_1_0_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_0_read ),
    .kernel_val_1_1_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_1_read ),
    .kernel_val_1_2_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_2_read ),
    .kernel_val_2_0_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_0_read ),
    .kernel_val_2_1_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_1_read ),
    .kernel_val_2_2_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_2_read ),
    .rows( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_rows ),
    .cols( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_cols )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_ST_st7_fsm_6 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(exitcond_fu_460_p2 == ap_const_lv1_0))) begin
            grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_ready)) begin
            grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        i_3_reg_1063 <= i_3_fu_466_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_i_fu_778_p2))) begin
        i_reg_178 <= i_3_reg_1063;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_57)) begin
        i_reg_178 <= ap_const_lv2_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        indvar_i_reg_408 <= ap_const_lv32_0;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        indvar_i_reg_408 <= indvar_next_i_reg_1187;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
        indvar_next1_i_reg_1098 <= indvar_next1_i_fu_508_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st5_fsm_4 == ap_CS_fsm)) begin
        indvar_next_i_reg_1187 <= indvar_next_i_fu_784_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        j_reg_289 <= ap_const_lv2_0;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        j_reg_289 <= indvar_next1_i_reg_1098;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_i_fu_778_p2))) begin
        newSel57_i_reg_1243 <= newSel57_i_fu_909_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_i_fu_778_p2))) begin
        or_cond36_i_reg_1215 <= or_cond36_i_fu_854_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_i_fu_778_p2))) begin
        or_cond38_i_reg_1221 <= or_cond38_i_fu_866_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_i_fu_778_p2))) begin
        or_cond41_i_reg_1228 <= or_cond41_i_fu_871_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        or_cond_i_reg_1126 <= or_cond_i_fu_576_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_i_fu_778_p2))) begin
        result_val13_1_i_reg_1233 <= result_val13_1_i_fu_885_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val13_2_i_reg_312 <= result_val13_6_i_reg_201;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        result_val13_2_i_reg_312 <= result_val13_1_i_reg_1233;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val13_5_i_reg_1139 <= result_val13_5_i_fu_596_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        result_val13_6_i_reg_201 <= temp_kernel_val_1_0_reg_82;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        result_val13_6_i_reg_201 <= result_val13_5_i_reg_1139;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val14_2_i_reg_324 <= result_val14_6_i_reg_212;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        result_val14_2_i_reg_324 <= newSel49_i_fu_968_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        result_val14_6_i_reg_212 <= temp_kernel_val_1_1_reg_94;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        result_val14_6_i_reg_212 <= newSel31_i_fu_679_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val1520_2_i_reg_348 <= result_val1520_6_i_reg_234;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        result_val1520_2_i_reg_348 <= newSel55_i_fu_1012_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        result_val1520_6_i_reg_234 <= temp_kernel_val_1_2_reg_118;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        result_val1520_6_i_reg_234 <= newSel37_i_fu_726_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val16_2_i_reg_336 <= result_val16_6_i_reg_223;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        result_val16_2_i_reg_336 <= newSel52_i_fu_990_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        result_val16_6_i_reg_223 <= temp_kernel_val_0_1_reg_106;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        result_val16_6_i_reg_223 <= newSel34_i_fu_702_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_i_fu_778_p2))) begin
        result_val26_1_i_reg_1238 <= result_val26_1_i_fu_893_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val26_2_i_reg_360 <= result_val26_6_i_reg_245;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        result_val26_2_i_reg_360 <= result_val26_1_i_reg_1238;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val26_5_i_reg_1144 <= result_val26_5_i_fu_604_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        result_val26_6_i_reg_245 <= temp_kernel_val_2_0_reg_130;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        result_val26_6_i_reg_245 <= result_val26_5_i_reg_1144;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val27_2_i_reg_384 <= result_val27_6_i_reg_267;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        result_val27_2_i_reg_384 <= newSel60_i_fu_1034_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        result_val27_6_i_reg_267 <= temp_kernel_val_2_1_reg_154;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        result_val27_6_i_reg_267 <= newSel42_i_fu_762_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val28_2_i_reg_396 <= result_val28_6_i_reg_278;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        result_val28_2_i_reg_396 <= newSel61_i_fu_1042_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        result_val28_6_i_reg_278 <= temp_kernel_val_2_2_reg_166;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        result_val28_6_i_reg_278 <= newSel43_i_fu_770_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val2_2_i_reg_300 <= result_val2_6_i_reg_190;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        result_val2_2_i_reg_300 <= newSel47_i_fu_953_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        result_val2_6_i_reg_190 <= temp_kernel_val_0_2_reg_70;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        result_val2_6_i_reg_190 <= newSel29_i_fu_663_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val_2_i_reg_372 <= result_val_6_i_reg_256;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        result_val_2_i_reg_372 <= newSel57_i_reg_1243;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        result_val_6_i_reg_256 <= temp_kernel_val_0_0_reg_142;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        result_val_6_i_reg_256 <= newSel39_i_fu_741_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        sel_tmp37_i_reg_1068 <= sel_tmp37_i_fu_472_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        sel_tmp46_i_reg_1079 <= sel_tmp46_i_fu_490_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        sel_tmp49_i_reg_1087 <= sel_tmp49_i_fu_496_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        sel_tmp58_i_reg_1103 <= sel_tmp58_i_fu_548_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        sel_tmp59_i_reg_1108 <= sel_tmp59_i_fu_554_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        sel_tmp61_i_reg_1114 <= sel_tmp61_i_fu_559_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_i_fu_778_p2))) begin
        sel_tmp84_i_reg_1192 <= sel_tmp84_i_fu_834_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_i_fu_778_p2))) begin
        sel_tmp86_i_reg_1198 <= sel_tmp86_i_fu_839_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_i_fu_778_p2))) begin
        sel_tmp87_i_reg_1204 <= sel_tmp87_i_fu_844_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_i_fu_778_p2))) begin
        sel_tmp88_i_reg_1209 <= sel_tmp88_i_fu_849_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_i_fu_778_p2))) begin
        temp_kernel_val_0_0_reg_142 <= result_val_2_i_reg_372;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_i_fu_778_p2))) begin
        temp_kernel_val_0_1_reg_106 <= result_val16_2_i_reg_336;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_i_fu_778_p2))) begin
        temp_kernel_val_0_2_reg_70 <= result_val2_2_i_reg_300;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_i_fu_778_p2))) begin
        temp_kernel_val_1_0_reg_82 <= result_val13_2_i_reg_312;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_i_fu_778_p2))) begin
        temp_kernel_val_1_1_reg_94 <= result_val14_2_i_reg_324;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_i_fu_778_p2))) begin
        temp_kernel_val_1_2_reg_118 <= result_val1520_2_i_reg_348;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_i_fu_778_p2))) begin
        temp_kernel_val_2_0_reg_130 <= result_val26_2_i_reg_360;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_i_fu_778_p2))) begin
        temp_kernel_val_2_1_reg_154 <= result_val27_2_i_reg_384;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_i_fu_778_p2))) begin
        temp_kernel_val_2_2_reg_166 <= result_val28_2_i_reg_396;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        tmp_64_i_reg_1119 <= tmp_64_i_fu_570_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        tmp_reg_1133 <= tmp_fu_582_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_CS_fsm or grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_ST_st7_fsm_6 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// p_dst_data_stream_0_V_write assign process. ///
always @ (ap_CS_fsm or grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_write)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) | (ap_ST_st7_fsm_6 == ap_CS_fsm))) begin
        p_dst_data_stream_0_V_write = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_write;
    end else begin
        p_dst_data_stream_0_V_write = ap_const_logic_0;
    end
end

/// p_dst_data_stream_1_V_write assign process. ///
always @ (ap_CS_fsm or grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_write)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) | (ap_ST_st7_fsm_6 == ap_CS_fsm))) begin
        p_dst_data_stream_1_V_write = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_write;
    end else begin
        p_dst_data_stream_1_V_write = ap_const_logic_0;
    end
end

/// p_dst_data_stream_2_V_write assign process. ///
always @ (ap_CS_fsm or grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_write)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) | (ap_ST_st7_fsm_6 == ap_CS_fsm))) begin
        p_dst_data_stream_2_V_write = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_write;
    end else begin
        p_dst_data_stream_2_V_write = ap_const_logic_0;
    end
end

/// p_src_data_stream_0_V_read assign process. ///
always @ (ap_CS_fsm or grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_read)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) | (ap_ST_st7_fsm_6 == ap_CS_fsm))) begin
        p_src_data_stream_0_V_read = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_read;
    end else begin
        p_src_data_stream_0_V_read = ap_const_logic_0;
    end
end

/// p_src_data_stream_1_V_read assign process. ///
always @ (ap_CS_fsm or grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_read)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) | (ap_ST_st7_fsm_6 == ap_CS_fsm))) begin
        p_src_data_stream_1_V_read = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_read;
    end else begin
        p_src_data_stream_1_V_read = ap_const_logic_0;
    end
end

/// p_src_data_stream_2_V_read assign process. ///
always @ (ap_CS_fsm or grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_read)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) | (ap_ST_st7_fsm_6 == ap_CS_fsm))) begin
        p_src_data_stream_2_V_read = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_read;
    end else begin
        p_src_data_stream_2_V_read = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or ap_sig_bdd_57 or exitcond_fu_460_p2 or exitcond7_fu_502_p2 or exitcond5_i_fu_778_p2 or grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~ap_sig_bdd_57) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if ((exitcond_fu_460_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        ap_ST_st3_fsm_2 : 
            if (~(ap_const_lv1_0 == exitcond7_fu_502_p2)) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        ap_ST_st4_fsm_3 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
        ap_ST_st5_fsm_4 : 
            if ((ap_const_lv1_0 == exitcond5_i_fu_778_p2)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        ap_ST_st6_fsm_5 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
        ap_ST_st7_fsm_6 : 
            if (~(ap_const_logic_0 == grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        default : 
            ap_NS_fsm = 'bx;
    endcase
end

/// ap_sig_bdd_57 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_57 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end
assign exitcond5_i_fu_778_p2 = (indvar_i_reg_408 == ap_const_lv32_0? 1'b1: 1'b0);
assign exitcond7_fu_502_p2 = (j_reg_289 == ap_const_lv2_3? 1'b1: 1'b0);
assign exitcond_fu_460_p2 = (i_reg_178 == ap_const_lv2_3? 1'b1: 1'b0);
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_cols = p_src_cols_V_read;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_0_read = temp_kernel_val_0_0_reg_142;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_1_read = temp_kernel_val_0_1_reg_106;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_2_read = temp_kernel_val_0_2_reg_70;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_0_read = temp_kernel_val_1_0_reg_82;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_1_read = temp_kernel_val_1_1_reg_94;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_2_read = temp_kernel_val_1_2_reg_118;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_0_read = temp_kernel_val_2_0_reg_130;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_1_read = temp_kernel_val_2_1_reg_154;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_2_read = temp_kernel_val_2_2_reg_166;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_full_n = p_dst_data_stream_0_V_full_n;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_full_n = p_dst_data_stream_1_V_full_n;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_full_n = p_dst_data_stream_2_V_full_n;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_dout = p_src_data_stream_0_V_dout;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_empty_n = p_src_data_stream_0_V_empty_n;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_dout = p_src_data_stream_1_V_dout;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_empty_n = p_src_data_stream_1_V_empty_n;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_dout = p_src_data_stream_2_V_dout;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_empty_n = p_src_data_stream_2_V_empty_n;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_rows = p_src_rows_V_read;
assign grp_fu_456_p2 = (sel_tmp37_i_reg_1068 | sel_tmp49_i_reg_1087);
assign i_3_fu_466_p2 = (i_reg_178 + ap_const_lv2_1);
assign indvar_next1_i_fu_508_p2 = (j_reg_289 + ap_const_lv2_1);
assign indvar_next_i_fu_784_p2 = (indvar_i_reg_408 + ap_const_lv32_1);
assign newSel27_i_fu_636_p3 = ((or_cond9_i_fu_620_p2)? result_val2_6_i_reg_190: newSel_i_fu_624_p3);
assign newSel28_i_fu_649_p3 = ((or_cond11_i_fu_631_p2)? result_val2_6_i_reg_190: newSel27_i_fu_636_p3);
assign newSel29_i_fu_663_p3 = ((or_cond13_i_fu_657_p2)? newSel28_i_fu_649_p3: result_val2_6_i_reg_190);
assign newSel30_i_fu_671_p3 = ((sel_tmp60_i_fu_612_p2)? ap_const_lv8_1: result_val14_6_i_reg_212);
assign newSel31_i_fu_679_p3 = ((or_cond11_i_fu_631_p2)? result_val14_6_i_reg_212: newSel30_i_fu_671_p3);
assign newSel32_i_fu_687_p3 = ((sel_tmp59_i_reg_1108)? ap_const_lv8_1: result_val16_6_i_reg_223);
assign newSel33_i_fu_694_p3 = ((or_cond9_i_fu_620_p2)? result_val16_6_i_reg_223: newSel32_i_fu_687_p3);
assign newSel34_i_fu_702_p3 = ((or_cond11_i_fu_631_p2)? result_val16_6_i_reg_223: newSel33_i_fu_694_p3);
assign newSel35_i_fu_710_p3 = ((sel_tmp60_i_fu_612_p2)? result_val1520_6_i_reg_234: ap_const_lv8_1);
assign newSel36_i_fu_718_p3 = ((or_cond9_i_fu_620_p2)? newSel35_i_fu_710_p3: result_val1520_6_i_reg_234);
assign newSel37_i_fu_726_p3 = ((or_cond11_i_fu_631_p2)? result_val1520_6_i_reg_234: newSel36_i_fu_718_p3);
assign newSel38_i_fu_734_p3 = ((tmp_64_i_reg_1119)? ap_const_lv8_1: result_val_6_i_reg_256);
assign newSel39_i_fu_741_p3 = ((or_cond_i_reg_1126)? result_val_6_i_reg_256: newSel38_i_fu_734_p3);
assign newSel40_i_fu_748_p3 = ((tmp_64_i_reg_1119)? result_val27_6_i_reg_267: ap_const_lv8_1);
assign newSel41_i_fu_755_p3 = ((or_cond_i_reg_1126)? result_val27_6_i_reg_267: newSel40_i_fu_748_p3);
assign newSel42_i_fu_762_p3 = ((or_cond11_i_fu_631_p2)? newSel41_i_fu_755_p3: result_val27_6_i_reg_267);
assign newSel43_i_fu_770_p3 = ((or_cond13_i_fu_657_p2)? result_val28_6_i_reg_278: ap_const_lv8_1);
assign newSel44_i_fu_921_p3 = ((sel_tmp84_i_reg_1192)? result_val2_2_i_reg_300: ap_const_lv8_0);
assign newSel45_i_fu_933_p3 = ((or_cond38_i_reg_1221)? result_val2_2_i_reg_300: newSel44_i_fu_921_p3);
assign newSel46_i_fu_940_p3 = ((or_cond40_i_fu_928_p2)? result_val2_2_i_reg_300: newSel45_i_fu_933_p3);
assign newSel47_i_fu_953_p3 = ((or_cond42_i_fu_948_p2)? newSel46_i_fu_940_p3: result_val2_2_i_reg_300);
assign newSel48_i_fu_961_p3 = ((sel_tmp86_i_reg_1198)? ap_const_lv8_0: result_val14_2_i_reg_324);
assign newSel49_i_fu_968_p3 = ((or_cond40_i_fu_928_p2)? result_val14_2_i_reg_324: newSel48_i_fu_961_p3);
assign newSel50_i_fu_976_p3 = ((sel_tmp84_i_reg_1192)? ap_const_lv8_0: result_val16_2_i_reg_336);
assign newSel51_i_fu_983_p3 = ((or_cond38_i_reg_1221)? result_val16_2_i_reg_336: newSel50_i_fu_976_p3);
assign newSel52_i_fu_990_p3 = ((or_cond40_i_fu_928_p2)? result_val16_2_i_reg_336: newSel51_i_fu_983_p3);
assign newSel53_i_fu_998_p3 = ((sel_tmp86_i_reg_1198)? result_val1520_2_i_reg_348: ap_const_lv8_0);
assign newSel54_i_fu_1005_p3 = ((or_cond38_i_reg_1221)? newSel53_i_fu_998_p3: result_val1520_2_i_reg_348);
assign newSel55_i_fu_1012_p3 = ((or_cond40_i_fu_928_p2)? result_val1520_2_i_reg_348: newSel54_i_fu_1005_p3);
assign newSel56_i_fu_901_p3 = ((sel_tmp88_i_fu_849_p2)? ap_const_lv8_0: result_val_2_i_reg_372);
assign newSel57_i_fu_909_p3 = ((or_cond36_i_fu_854_p2)? result_val_2_i_reg_372: newSel56_i_fu_901_p3);
assign newSel58_i_fu_1020_p3 = ((sel_tmp88_i_reg_1209)? result_val27_2_i_reg_384: ap_const_lv8_0);
assign newSel59_i_fu_1027_p3 = ((or_cond36_i_reg_1215)? result_val27_2_i_reg_384: newSel58_i_fu_1020_p3);
assign newSel60_i_fu_1034_p3 = ((or_cond40_i_fu_928_p2)? newSel59_i_fu_1027_p3: result_val27_2_i_reg_384);
assign newSel61_i_fu_1042_p3 = ((or_cond42_i_fu_948_p2)? result_val28_2_i_reg_396: ap_const_lv8_0);
assign newSel_i_fu_624_p3 = ((sel_tmp59_i_reg_1108)? result_val2_6_i_reg_190: ap_const_lv8_1);
assign or_cond11_i_fu_631_p2 = (or_cond_i_reg_1126 | or_cond8_i_fu_616_p2);
assign or_cond12_i_fu_644_p2 = (tmp_reg_1133 & grp_fu_456_p2);
assign or_cond13_i_fu_657_p2 = (or_cond11_i_fu_631_p2 | or_cond12_i_fu_644_p2);
assign or_cond36_i_fu_854_p2 = (sel_tmp77_i_fu_805_p2 | sel_tmp73_i_fu_800_p2);
assign or_cond37_i_fu_917_p2 = (sel_tmp88_i_reg_1209 | sel_tmp87_i_reg_1204);
assign or_cond38_i_fu_866_p2 = (sel_tmp37_i_reg_1068 & tmp3_fu_860_p2);
assign or_cond40_i_fu_928_p2 = (or_cond36_i_reg_1215 | or_cond37_i_fu_917_p2);
assign or_cond41_i_fu_871_p2 = (tmp3_fu_860_p2 & grp_fu_456_p2);
assign or_cond42_i_fu_948_p2 = (or_cond40_i_fu_928_p2 | or_cond41_i_reg_1228);
assign or_cond8_i_fu_616_p2 = (tmp_64_i_reg_1119 | sel_tmp61_i_reg_1114);
assign or_cond9_i_fu_620_p2 = (sel_tmp37_i_reg_1068 & tmp_reg_1133);
assign or_cond_i_fu_576_p2 = (sel_tmp47_i_fu_525_p2 | sel_tmp39_i_fu_520_p2);
assign p_dst_data_stream_0_V_din = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_din;
assign p_dst_data_stream_1_V_din = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_din;
assign p_dst_data_stream_2_V_din = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_din;
assign result_val13_1_i_fu_885_p3 = ((sel_tmp77_i_fu_805_p2)? result_val13_2_i_reg_312: sel_tmp89_i_fu_877_p3);
assign result_val13_5_i_fu_596_p3 = ((sel_tmp47_i_fu_525_p2)? result_val13_6_i_reg_201: sel_tmp62_i_fu_588_p3);
assign result_val26_1_i_fu_893_p3 = ((sel_tmp77_i_fu_805_p2)? ap_const_lv8_0: result_val26_2_i_reg_360);
assign result_val26_5_i_fu_604_p3 = ((sel_tmp47_i_fu_525_p2)? ap_const_lv8_1: result_val26_6_i_reg_245);
assign sel_tmp37_i_fu_472_p2 = (i_reg_178 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp38_i_fu_514_p2 = (j_reg_289 == ap_const_lv2_0? 1'b1: 1'b0);
assign sel_tmp39_i_fu_520_p2 = (sel_tmp37_i_reg_1068 & sel_tmp38_i_fu_514_p2);
assign sel_tmp44_i_fu_478_p2 = (i_reg_178 != ap_const_lv2_0? 1'b1: 1'b0);
assign sel_tmp45_i_fu_484_p2 = (i_reg_178 != ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp46_i_fu_490_p2 = (sel_tmp44_i_fu_478_p2 & sel_tmp45_i_fu_484_p2);
assign sel_tmp47_i_fu_525_p2 = (sel_tmp46_i_reg_1079 & sel_tmp38_i_fu_514_p2);
assign sel_tmp49_i_fu_496_p2 = (i_reg_178 == ap_const_lv2_0? 1'b1: 1'b0);
assign sel_tmp52_i_fu_530_p2 = (j_reg_289 != ap_const_lv2_0? 1'b1: 1'b0);
assign sel_tmp54_i_fu_536_p2 = (j_reg_289 != ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp58_i_fu_548_p2 = (j_reg_289 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp59_i_fu_554_p2 = (sel_tmp49_i_reg_1087 & sel_tmp58_i_fu_548_p2);
assign sel_tmp60_i_fu_612_p2 = (sel_tmp37_i_reg_1068 & sel_tmp58_i_reg_1103);
assign sel_tmp61_i_fu_559_p2 = (sel_tmp46_i_reg_1079 & sel_tmp58_i_fu_548_p2);
assign sel_tmp62_i_fu_588_p3 = ((sel_tmp39_i_fu_520_p2)? ap_const_lv8_1: result_val13_6_i_reg_201);
assign sel_tmp72_i_fu_794_p2 = (tmp_103_fu_790_p1 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp73_i_fu_800_p2 = (sel_tmp37_i_reg_1068 & sel_tmp72_i_fu_794_p2);
assign sel_tmp77_i_fu_805_p2 = (sel_tmp46_i_reg_1079 & sel_tmp72_i_fu_794_p2);
assign sel_tmp80_i_fu_810_p2 = (tmp_103_fu_790_p1 != ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp81_i_fu_816_p2 = (tmp_103_fu_790_p1 != ap_const_lv2_2? 1'b1: 1'b0);
assign sel_tmp83_i_fu_828_p2 = (tmp_103_fu_790_p1 == ap_const_lv2_2? 1'b1: 1'b0);
assign sel_tmp84_i_fu_834_p2 = (sel_tmp49_i_reg_1087 & sel_tmp83_i_fu_828_p2);
assign sel_tmp86_i_fu_839_p2 = (sel_tmp37_i_reg_1068 & sel_tmp83_i_fu_828_p2);
assign sel_tmp87_i_fu_844_p2 = (sel_tmp46_i_reg_1079 & sel_tmp83_i_fu_828_p2);
assign sel_tmp88_i_fu_849_p2 = (sel_tmp49_i_reg_1087 & sel_tmp72_i_fu_794_p2);
assign sel_tmp89_i_fu_877_p3 = ((sel_tmp73_i_fu_800_p2)? ap_const_lv8_0: result_val13_2_i_reg_312);
assign tmp1_i_fu_542_p2 = (sel_tmp52_i_fu_530_p2 & sel_tmp54_i_fu_536_p2);
assign tmp29_i_fu_822_p2 = (sel_tmp80_i_fu_810_p2 & sel_tmp81_i_fu_816_p2);
assign tmp3_fu_860_p2 = (tmp29_i_fu_822_p2 | sel_tmp83_i_fu_828_p2);
assign tmp_103_fu_790_p1 = indvar_i_reg_408[1:0];
assign tmp_63_i_fu_564_p2 = (i_reg_178 | j_reg_289);
assign tmp_64_i_fu_570_p2 = (tmp_63_i_fu_564_p2 == ap_const_lv2_0? 1'b1: 1'b0);
assign tmp_fu_582_p2 = (tmp1_i_fu_542_p2 | sel_tmp58_i_fu_548_p2);


endmodule //Erode_16_16_1080_1920_s

