// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.1
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CvtColor_0_16_16_1080_1920_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_rows_V_read,
        p_src_cols_V_read,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [11:0] p_src_rows_V_read;
input  [11:0] p_src_cols_V_read;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;
reg    ap_done_reg = 1'b0;
reg   [1:0] ap_CS_fsm = 2'b00;
reg   [11:0] j_reg_146;
reg    ap_sig_bdd_56;
wire   [11:0] i_2_fu_163_p2;
reg   [11:0] i_2_reg_289;
wire   [0:0] exitcond3_fu_169_p2;
reg   [0:0] exitcond3_reg_294;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_sig_bdd_80;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond3_reg_294_pp0_it6;
reg    ap_sig_bdd_104;
reg    ap_reg_ppiten_pp0_it7 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond3_reg_294_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond3_reg_294_pp0_it2;
reg   [0:0] ap_reg_ppstg_exitcond3_reg_294_pp0_it3;
reg   [0:0] ap_reg_ppstg_exitcond3_reg_294_pp0_it4;
reg   [0:0] ap_reg_ppstg_exitcond3_reg_294_pp0_it5;
wire   [11:0] j_1_fu_174_p2;
reg   [7:0] tmp_100_reg_303;
reg   [7:0] tmp_101_reg_308;
reg   [7:0] ap_reg_ppstg_tmp_101_reg_308_pp0_it2;
reg   [7:0] tmp_102_reg_313;
wire   [25:0] grp_fu_183_p2;
reg   [25:0] r_V_reg_333;
wire   [27:0] grp_fu_192_p2;
reg   [27:0] g_V_reg_338;
wire   [28:0] grp_fu_201_p2;
reg   [28:0] b_V_reg_343;
wire   [27:0] r_V_1_fu_210_p2;
reg   [27:0] r_V_1_reg_348;
reg   [7:0] tmp_51_reg_353;
reg   [0:0] qbit_reg_358;
wire   [0:0] exitcond4_fu_158_p2;
reg   [11:0] i_reg_135;
wire   [7:0] p_d_val_0_fu_265_p3;
wire   [7:0] grp_fu_183_p0;
wire   [17:0] grp_fu_183_p1;
wire   [7:0] grp_fu_192_p0;
wire   [19:0] grp_fu_192_p1;
wire   [7:0] grp_fu_201_p0;
wire   [20:0] grp_fu_201_p1;
wire   [27:0] lhs_V1_i_cast_fu_207_p1;
wire   [28:0] lhs_V_1_i_cast_fu_215_p1;
wire   [28:0] r_V_2_fu_218_p2;
wire   [8:0] p_Val2_8_i_cast_fu_241_p1;
wire   [8:0] tmp_7_i_cast_fu_244_p1;
wire   [8:0] p_Val2_s_fu_247_p2;
wire   [0:0] tmp_98_fu_253_p3;
wire   [7:0] tmp_99_fu_261_p1;
reg    grp_fu_183_ce;
reg    grp_fu_192_ce;
reg    grp_fu_201_ce;
reg   [1:0] ap_NS_fsm;
wire   [25:0] grp_fu_183_p00;
wire   [27:0] grp_fu_192_p00;
wire   [28:0] grp_fu_201_p00;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 2'b00;
parameter    ap_ST_st2_fsm_1 = 2'b1;
parameter    ap_ST_pp0_stg0_fsm_2 = 2'b10;
parameter    ap_ST_st11_fsm_3 = 2'b11;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_const_lv26_3A5E3 = 26'b111010010111100011;
parameter    ap_const_lv28_99168 = 28'b10011001000101101000;
parameter    ap_const_lv29_12C8B4 = 29'b100101100100010110100;
parameter    ap_const_lv32_15 = 32'b10101;
parameter    ap_const_lv32_1C = 32'b11100;
parameter    ap_const_lv32_14 = 32'b10100;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_true = 1'b1;


image_processor_mul_8ns_18ns_26_3 #(
    .ID( 21 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 26 ))
image_processor_mul_8ns_18ns_26_3_U21(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_183_p0 ),
    .din1( grp_fu_183_p1 ),
    .ce( grp_fu_183_ce ),
    .dout( grp_fu_183_p2 )
);

image_processor_mul_8ns_20ns_28_3 #(
    .ID( 22 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 20 ),
    .dout_WIDTH( 28 ))
image_processor_mul_8ns_20ns_28_3_U22(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_192_p0 ),
    .din1( grp_fu_192_p1 ),
    .ce( grp_fu_192_ce ),
    .dout( grp_fu_192_p2 )
);

image_processor_mul_8ns_21ns_29_3 #(
    .ID( 23 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 21 ),
    .dout_WIDTH( 29 ))
image_processor_mul_8ns_21ns_29_3_U23(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_201_p0 ),
    .din1( grp_fu_201_p1 ),
    .ce( grp_fu_201_ce ),
    .dout( grp_fu_201_p2 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond4_fu_158_p2))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(exitcond3_fu_169_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_158_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (exitcond3_fu_169_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_158_p2)) | ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(exitcond3_fu_169_p2 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_158_p2))) begin
            ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it3 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_158_p2))) begin
            ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it4 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_158_p2))) begin
            ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it5 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_158_p2))) begin
            ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it6 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_158_p2))) begin
            ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it7 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it7
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_158_p2))) begin
            ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_exitcond3_reg_294_pp0_it1 <= exitcond3_reg_294;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_exitcond3_reg_294_pp0_it2 <= ap_reg_ppstg_exitcond3_reg_294_pp0_it1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_exitcond3_reg_294_pp0_it3 <= ap_reg_ppstg_exitcond3_reg_294_pp0_it2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_exitcond3_reg_294_pp0_it4 <= ap_reg_ppstg_exitcond3_reg_294_pp0_it3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_exitcond3_reg_294_pp0_it5 <= ap_reg_ppstg_exitcond3_reg_294_pp0_it4;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_exitcond3_reg_294_pp0_it6 <= ap_reg_ppstg_exitcond3_reg_294_pp0_it5;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_tmp_101_reg_308_pp0_it2 <= tmp_101_reg_308;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it4))) begin
        b_V_reg_343 <= grp_fu_201_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        exitcond3_reg_294 <= exitcond3_fu_169_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it3))) begin
        g_V_reg_338 <= grp_fu_192_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        i_2_reg_289 <= i_2_fu_163_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st11_fsm_3 == ap_CS_fsm)) begin
        i_reg_135 <= i_2_reg_289;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_56)) begin
        i_reg_135 <= ap_const_lv12_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (exitcond3_fu_169_p2 == ap_const_lv1_0))) begin
        j_reg_146 <= j_1_fu_174_p2;
    end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_158_p2))) begin
        j_reg_146 <= ap_const_lv12_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it5))) begin
        qbit_reg_358 <= r_V_2_fu_218_p2[ap_const_lv32_14];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it4))) begin
        r_V_1_reg_348 <= r_V_1_fu_210_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it3))) begin
        r_V_reg_333 <= grp_fu_183_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond3_reg_294 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        tmp_100_reg_303 <= p_src_data_stream_0_V_dout;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond3_reg_294 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        tmp_101_reg_308 <= p_src_data_stream_1_V_dout;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond3_reg_294 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        tmp_102_reg_313 <= p_src_data_stream_2_V_dout;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it5))) begin
        tmp_51_reg_353 <= {{r_V_2_fu_218_p2[ap_const_lv32_1C : ap_const_lv32_15]}};
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_CS_fsm or exitcond4_fu_158_p2)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond4_fu_158_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or exitcond4_fu_158_p2)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond4_fu_158_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// grp_fu_183_ce assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_80 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_104 or ap_reg_ppiten_pp0_it7 or ap_reg_ppstg_exitcond3_reg_294_pp0_it1 or ap_reg_ppstg_exitcond3_reg_294_pp0_it2 or ap_reg_ppstg_exitcond3_reg_294_pp0_it3)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ((ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it1) | (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it2) | (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it3)))) begin
        grp_fu_183_ce = ap_const_logic_1;
    end else begin
        grp_fu_183_ce = ap_const_logic_0;
    end
end

/// grp_fu_192_ce assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_80 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_104 or ap_reg_ppiten_pp0_it7 or ap_reg_ppstg_exitcond3_reg_294_pp0_it1 or ap_reg_ppstg_exitcond3_reg_294_pp0_it2 or ap_reg_ppstg_exitcond3_reg_294_pp0_it3)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ((ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it1) | (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it2) | (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it3)))) begin
        grp_fu_192_ce = ap_const_logic_1;
    end else begin
        grp_fu_192_ce = ap_const_logic_0;
    end
end

/// grp_fu_201_ce assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_80 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_104 or ap_reg_ppiten_pp0_it7 or ap_reg_ppstg_exitcond3_reg_294_pp0_it2 or ap_reg_ppstg_exitcond3_reg_294_pp0_it3 or ap_reg_ppstg_exitcond3_reg_294_pp0_it4)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ((ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it2) | (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it3) | (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it4)))) begin
        grp_fu_201_ce = ap_const_logic_1;
    end else begin
        grp_fu_201_ce = ap_const_logic_0;
    end
end

/// p_dst_data_stream_0_V_write assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_80 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond3_reg_294_pp0_it6 or ap_sig_bdd_104 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it6) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        p_dst_data_stream_0_V_write = ap_const_logic_1;
    end else begin
        p_dst_data_stream_0_V_write = ap_const_logic_0;
    end
end

/// p_dst_data_stream_1_V_write assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_80 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond3_reg_294_pp0_it6 or ap_sig_bdd_104 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it6) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        p_dst_data_stream_1_V_write = ap_const_logic_1;
    end else begin
        p_dst_data_stream_1_V_write = ap_const_logic_0;
    end
end

/// p_dst_data_stream_2_V_write assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_80 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond3_reg_294_pp0_it6 or ap_sig_bdd_104 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it6) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        p_dst_data_stream_2_V_write = ap_const_logic_1;
    end else begin
        p_dst_data_stream_2_V_write = ap_const_logic_0;
    end
end

/// p_src_data_stream_0_V_read assign process. ///
always @ (ap_CS_fsm or exitcond3_reg_294 or ap_sig_bdd_80 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_104 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond3_reg_294 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        p_src_data_stream_0_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_0_V_read = ap_const_logic_0;
    end
end

/// p_src_data_stream_1_V_read assign process. ///
always @ (ap_CS_fsm or exitcond3_reg_294 or ap_sig_bdd_80 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_104 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond3_reg_294 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        p_src_data_stream_1_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_1_V_read = ap_const_logic_0;
    end
end

/// p_src_data_stream_2_V_read assign process. ///
always @ (ap_CS_fsm or exitcond3_reg_294 or ap_sig_bdd_80 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_104 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond3_reg_294 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        p_src_data_stream_2_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_2_V_read = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or ap_sig_bdd_56 or exitcond3_fu_169_p2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_80 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it6 or ap_sig_bdd_104 or ap_reg_ppiten_pp0_it7 or exitcond4_fu_158_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~ap_sig_bdd_56) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if (~(ap_const_lv1_0 == exitcond4_fu_158_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        ap_ST_pp0_stg0_fsm_2 : 
            if ((~((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it6)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(exitcond3_fu_169_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if ((((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it6)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_80 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(exitcond3_fu_169_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st11_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        ap_ST_st11_fsm_3 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
        default : 
            ap_NS_fsm = 'bx;
    endcase
end

/// ap_sig_bdd_104 assign process. ///
always @ (p_dst_data_stream_0_V_full_n or p_dst_data_stream_1_V_full_n or p_dst_data_stream_2_V_full_n or ap_reg_ppstg_exitcond3_reg_294_pp0_it6)
begin
    ap_sig_bdd_104 = (((p_dst_data_stream_0_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it6)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it6) & (p_dst_data_stream_1_V_full_n == ap_const_logic_0)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_294_pp0_it6) & (p_dst_data_stream_2_V_full_n == ap_const_logic_0)));
end

/// ap_sig_bdd_56 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_56 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

/// ap_sig_bdd_80 assign process. ///
always @ (p_src_data_stream_0_V_empty_n or p_src_data_stream_1_V_empty_n or p_src_data_stream_2_V_empty_n or exitcond3_reg_294)
begin
    ap_sig_bdd_80 = (((p_src_data_stream_0_V_empty_n == ap_const_logic_0) & (exitcond3_reg_294 == ap_const_lv1_0)) | ((exitcond3_reg_294 == ap_const_lv1_0) & (p_src_data_stream_1_V_empty_n == ap_const_logic_0)) | ((exitcond3_reg_294 == ap_const_lv1_0) & (p_src_data_stream_2_V_empty_n == ap_const_logic_0)));
end
assign exitcond3_fu_169_p2 = (j_reg_146 == p_src_cols_V_read? 1'b1: 1'b0);
assign exitcond4_fu_158_p2 = (i_reg_135 == p_src_rows_V_read? 1'b1: 1'b0);
assign grp_fu_183_p0 = grp_fu_183_p00;
assign grp_fu_183_p00 = $unsigned(tmp_102_reg_313);
assign grp_fu_183_p1 = ap_const_lv26_3A5E3;
assign grp_fu_192_p0 = grp_fu_192_p00;
assign grp_fu_192_p00 = $unsigned(tmp_100_reg_303);
assign grp_fu_192_p1 = ap_const_lv28_99168;
assign grp_fu_201_p0 = grp_fu_201_p00;
assign grp_fu_201_p00 = $unsigned(ap_reg_ppstg_tmp_101_reg_308_pp0_it2);
assign grp_fu_201_p1 = ap_const_lv29_12C8B4;
assign i_2_fu_163_p2 = (i_reg_135 + ap_const_lv12_1);
assign j_1_fu_174_p2 = (j_reg_146 + ap_const_lv12_1);
assign lhs_V1_i_cast_fu_207_p1 = $unsigned(r_V_reg_333);
assign lhs_V_1_i_cast_fu_215_p1 = $unsigned(r_V_1_reg_348);
assign p_Val2_8_i_cast_fu_241_p1 = $unsigned(tmp_51_reg_353);
assign p_Val2_s_fu_247_p2 = (p_Val2_8_i_cast_fu_241_p1 + tmp_7_i_cast_fu_244_p1);
assign p_d_val_0_fu_265_p3 = ((tmp_98_fu_253_p3)? ap_const_lv8_FF: tmp_99_fu_261_p1);
assign p_dst_data_stream_0_V_din = p_d_val_0_fu_265_p3;
assign p_dst_data_stream_1_V_din = p_d_val_0_fu_265_p3;
assign p_dst_data_stream_2_V_din = p_d_val_0_fu_265_p3;
assign r_V_1_fu_210_p2 = (g_V_reg_338 + lhs_V1_i_cast_fu_207_p1);
assign r_V_2_fu_218_p2 = (b_V_reg_343 + lhs_V_1_i_cast_fu_215_p1);
assign tmp_7_i_cast_fu_244_p1 = $unsigned(qbit_reg_358);
assign tmp_98_fu_253_p3 = p_Val2_s_fu_247_p2[ap_const_lv32_8];
assign tmp_99_fu_261_p1 = p_Val2_s_fu_247_p2[7:0];


endmodule //CvtColor_0_16_16_1080_1920_s

